[build]
  command = "pnpm run build"
  publish = ".next"

[functions]
  node_bundler = "pnpm"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

[dev]
  command = "pnpm run dev"
  port = 3000
